# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1493025482);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1491294429);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1491386491);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1493022689);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 15);
user_pref("browser.newtabpage.blocked", "{\"f+A/jj9TUrKNy0U6/gN1YQ==\":1,\"cPaSH+rhX595scwpmjduyw==\":1}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 6);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140410211157");
user_pref("browser.slowStartup.averageTime", 2819);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20140410211157");
user_pref("browser.startup.homepage_override.mstone", "28.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":2,\"passwords\":4}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1493021874109");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1493021876092");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1493108276092");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1491207609319");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1491236411455");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-implicit-time-elapsed");
user_pref("datareporting.policy.firstRunTime", "1486458849714");
user_pref("datareporting.sessions.current.activeTicks", 36);
user_pref("datareporting.sessions.current.firstPaint", 895);
user_pref("datareporting.sessions.current.main", 21);
user_pref("datareporting.sessions.current.sessionRestored", 1023);
user_pref("datareporting.sessions.current.startTime", "1493025361481");
user_pref("datareporting.sessions.current.totalTime", 181);
user_pref("datareporting.sessions.currentIndex", 37);
user_pref("datareporting.sessions.previous.35", "{\"s\":1493021805545,\"a\":5,\"t\":75,\"c\":true,\"m\":1081,\"fp\":5727,\"sr\":6545}");
user_pref("datareporting.sessions.previous.36", "{\"s\":1493022568882,\"a\":30,\"t\":226,\"c\":true,\"m\":31,\"fp\":847,\"sr\":958}");
user_pref("datareporting.sessions.prunedIndex", 34);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 6);
user_pref("extensions.bootstrappedAddons", "{\"webapps-team@lists.launchpad.net\":{\"version\":\"3.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\"}}");
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:2.8,%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2013.09.20.beta,online-accounts%40lists.launchpad.net:0.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:28.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150311.01");
user_pref("extensions.installCache", "[{\"name\":\"app-system-local\",\"addons\":{\"online-accounts@lists.launchpad.net\":{\"descriptor\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"mtime\":1397697923000,\"rdfTime\":1390969638000}}},{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1397697923000,\"rdfTime\":1381435136000},\"webapps-team@lists.launchpad.net\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"mtime\":1397697923000,\"rdfTime\":1397665356000},\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"mtime\":1397697923000,\"rdfTime\":1379719396000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1397697857000,\"rdfTime\":1397165557000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1485977112000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1485977112000}}}]");
user_pref("extensions.lastAppVersion", "28.0");
user_pref("extensions.lastPlatformVersion", "28.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140410211157");
user_pref("gecko.mstone", "28.0");
user_pref("gfx.blacklist.direct2d", 4);
user_pref("gfx.blacklist.layers.direct3d10", 4);
user_pref("gfx.blacklist.layers.direct3d10-1", 4);
user_pref("gfx.blacklist.layers.direct3d9", 4);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.stagefright", 4);
user_pref("gfx.blacklist.webgl.angle", 4);
user_pref("gfx.blacklist.webgl.msaa", 4);
user_pref("gfx.blacklist.webgl.opengl", 4);
user_pref("idle.lastDailyNotification", 1493025594);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1493021874);
user_pref("places.history.expiration.transient_current_max_pages", 52570);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1490607165);
user_pref("toolkit.startup.last_success", 1493025361);
user_pref("toolkit.telemetry.previousBuildID", "20140410211157");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1495613813);
